export const info1 = {
    "Configuration": "DPD",
    "Transmission": "Automatic",
    "Description": "DPD",
    "Body Style": "Van",
    "Drivetrain": "RWD",
    "Performance Class": "3",
    "default_color": "Pearl White",
    "Config Type": "Factory"
}

export const expectedInfo1 = {
    "Configuration": "DPD",
    "Transmission": "Automatic",
    "Description": "DPD",
    "Body Style": "Van",
    "Drivetrain": "RWD",
    "Performance Class": "3",
    "default_color": "Pearl White",
    "Config Type": "Police"
}

export const pc1 = {
    "format": 2,
    "licenseName": "Deltatroopers",
    "model": "van",
    "paints": [
        {
            "baseColor": [
                0.829999983,
                0.829999983,
                0.829999983,
                1.20000005
            ],
            "clearcoat": "1",
            "clearcoatRoughness": "0.0799999982",
            "metallic": "0.300000012",
            "roughness": "0.600000024"
        },
        {
            "baseColor": [
                0.800000012,
                0.100000001,
                0.100000001,
                1.20000005
            ],
            "clearcoat": "1",
            "clearcoatRoughness": "0.0799999982",
            "metallic": "0",
            "roughness": "1"
        },
        {
            "baseColor": [
                0.829999983,
                0.829999983,
                0.829999983,
                1.20000005
            ],
            "clearcoat": "1",
            "clearcoatRoughness": "0.0799999982",
            "metallic": "0.300000012",
            "roughness": "0.600000024"
        }
    ],
    "parts": {
        "brakepad_F": "brakepad_F_premium",
        "brakepad_R": "brakepad_R_premium",
        "gps": "",
        "licenseplate_design_2_1": "",
        "linelock": "",
        "n2o_system": "",
        "paint_design": "van_skin_chrono",
        "pickup_engine_v8_ecu": "pickup_engine_v8_ecu_late",
        "pickup_engine_v8_internals": "pickup_engine_v8_internals",
        "pickup_enginemounts": "pickup_enginemounts",
        "pickup_oilpan_v8": "pickup_oilpan_v8",
        "pickup_receiver_attachment": "pickup_receiver_ball",
        "pickup_reversewarn": "",
        "pickup_sparetire": "pickup_sparetire_6l",
        "pickup_towhitch": "pickup_towhitch",
        "skin_glass": "",
        "skin_interior": "van_skin_interior",
        "soundscape_horn": "soundscape_horn_3",
        "soundscape_siren": "soundscape_siren_3",
        "tire_F_16x7_alt": "tire_F_245_75_16_alt_heavy",
        "tire_R_16x7_alt": "tire_R_245_75_16_alt_heavy",
        "trailer_small": "",
        "van_ABS": "van_ABS",
        "van_ESC": "van_ESC",
        "van_ac": "van_ac",
        "van_body": "van_body_sidedoor",
        "van_brake_F": "van_brake_F",
        "van_brake_R": "van_brake_R",
        "van_bumper_F": "van_bumper_F_late_alt",
        "van_bumper_F_lip_late": "",
        "van_bumper_R": "van_bumper_R_late_alt",
        "van_bumper_accessory_F_late": "",
        "van_converter": "van_converter_heavy",
        "van_differential_R": "van_differential_R_LSD",
        "van_door_FL": "van_door_FL",
        "van_door_FR": "van_door_FR",
        "van_doorglass_L": "van_doorglass_L",
        "van_doorglass_R": "van_doorglass_R",
        "van_doorpanel_FL": "van_doorpanel_FL",
        "van_doorpanel_FR": "van_doorpanel_FR",
        "van_driveshaft_R": "van_driveshaft_R",
        "van_engine": "van_engine_v8_5.5",
        "van_exhaust_v8": "van_exhaust_v8",
        "van_fascia_F": "van_fascia_F_late",
        "van_fender_L": "van_fender_L",
        "van_fender_R": "van_fender_R",
        "van_fenderflare_FL": "",
        "van_fenderflare_FR": "",
        "van_fenderflare_RL": "",
        "van_fenderflare_RR_sidedoor": "",
        "van_finaldrive_R": "van_finaldrive_R_355",
        "van_frame": "van_frame",
        "van_fueltank": "van_fueltank",
        "van_grille_F_late": "van_grille_F_late",
        "van_header": "van_exhmanifold",
        "van_headlight_L_late": "van_headlight_L_late",
        "van_headlight_R_late": "van_headlight_R_late",
        "van_hood": "van_hood_late",
        "van_hub_F": "van_hub_F_6",
        "van_hub_R": "van_hub_R_6",
        "van_intake_v8": "van_intake_v8_late",
        "van_intcarpet_roof": "",
        "van_interior": "van_interior",
        "van_lettering_doors_F": "van_lettering_doors_F_h25",
        "van_lettering_reardoor_L": "van_lettering_gavril_reardoor_L",
        "van_lettering_reardoor_R": "van_lettering_H25_reardoor_R",
        "van_licenseplate_F_late": "van_licenseplate_F_late",
        "van_licenseplate_R_late": "van_licenseplate_R_late",
        "van_lightbar": "",
        "van_load": "",
        "van_mirror_L": "van_mirror_L",
        "van_mirror_R": "van_mirror_R",
        "van_mod": "",
        "van_muffler": "van_muffler",
        "van_power_steering": "",
        "van_radiator": "van_radiator_heavy",
        "van_radio": "van_radio",
        "van_reardoor_L": "van_reardoor_L",
        "van_reardoor_R": "van_reardoor_R",
        "van_reardoorglass_L": "van_reardoorglass_L",
        "van_reardoorglass_R": "van_reardoorglass_R",
        "van_reardoorpanel_L": "",
        "van_reardoorpanel_R": "",
        "van_rollcage": "",
        "van_roof": "van_roof",
        "van_roof_accessory": "",
        "van_runningboard": "van_runningboard",
        "van_seat_FL": "van_seat_FL",
        "van_seat_FR": "van_seat_FR",
        "van_shifter": "van_shifter_A",
        "van_shock_F": "van_shock_F_medium",
        "van_shock_R": "van_shock_R_medium",
        "van_sidedoor_FR": "van_sidedoor_FR",
        "van_sidedoor_RR": "van_sidedoor_RR",
        "van_snorkel": "",
        "van_spring_F": "van_spring_F_medium",
        "van_spring_R": "van_spring_R_medium",
        "van_steer": "van_steer_facelift",
        "van_steering_SFA": "van_steering_SFA",
        "van_suspension_F": "van_beamaxle_F",
        "van_suspension_R": "van_axle_R",
        "van_swaybar_F_SFA": "",
        "van_swaybar_R": "",
        "van_taillight_L": "van_taillight_L",
        "van_taillight_R": "van_taillight_R",
        "van_taillightguard_L": "",
        "van_taillightguard_R": "",
        "van_transfer_case": "van_transfer_case_RWD",
        "van_transmission": "van_transmission_6A",
        "van_tubs": "van_tubs",
        "van_valance_F": "van_valance_F_late",
        "van_wheeldata_F": "van_wheeldata_F",
        "van_wheeldata_R": "van_wheeldata_R",
        "van_windshield": "van_windshield",
        "wheel_F_6": "roamer_alloy_16x7_F",
        "wheel_R_6": "roamer_alloy_16x7_R"
    },
    "vars": {
        "$steer_center_F2": 0.0001,
        "$tirepressure_F": 30,
        "$tirepressure_R": 30
    }
}

export const expectedPC1 = {
    "format": 2,
    "licenseName": "Deltatroopers",
    "model": "van",
    "paints": [
        {
            "baseColor": [
                0.829999983,
                0.829999983,
                0.829999983,
                1.20000005
            ],
            "clearcoat": "1",
            "clearcoatRoughness": "0.0799999982",
            "metallic": "0.300000012",
            "roughness": "0.600000024"
        },
        {
            "baseColor": [
                0.800000012,
                0.100000001,
                0.100000001,
                1.20000005
            ],
            "clearcoat": "1",
            "clearcoatRoughness": "0.0799999982",
            "metallic": "0",
            "roughness": "1"
        },
        {
            "baseColor": [
                0.829999983,
                0.829999983,
                0.829999983,
                1.20000005
            ],
            "clearcoat": "1",
            "clearcoatRoughness": "0.0799999982",
            "metallic": "0.300000012",
            "roughness": "0.600000024"
        }
    ],
    "parts": {
        "brakepad_F": "brakepad_F_premium",
        "brakepad_R": "brakepad_R_premium",
        "gps": "",
        "licenseplate_design_2_1": "",
        "linelock": "",
        "n2o_system": "",
        "paint_design": "van_skin_chrono",
        "pickup_engine_v8_ecu": "pickup_engine_v8_ecu_late",
        "pickup_engine_v8_internals": "pickup_engine_v8_internals",
        "pickup_enginemounts": "pickup_enginemounts",
        "pickup_oilpan_v8": "pickup_oilpan_v8",
        "pickup_receiver_attachment": "pickup_receiver_ball",
        "pickup_reversewarn": "",
        "pickup_sparetire": "pickup_sparetire_6l",
        "pickup_towhitch": "pickup_towhitch",
        "skin_glass": "",
        "skin_interior": "van_skin_interior",
        "soundscape_horn": "soundscape_horn_3",
        "soundscape_siren": "soundscape_siren_gendarmerie",
        "tire_F_16x7_alt": "tire_F_245_75_16_alt_heavy",
        "tire_R_16x7_alt": "tire_R_245_75_16_alt_heavy",
        "trailer_small": "",
        "van_ABS": "van_ABS",
        "van_ESC": "van_ESC",
        "van_ac": "van_ac",
        "van_body": "van_body_sidedoor",
        "van_brake_F": "van_brake_F",
        "van_brake_R": "van_brake_R",
        "van_bumper_F": "van_bumper_F_late_alt",
        "van_bumper_F_lip_late": "",
        "van_bumper_R": "van_bumper_R_late_alt",
        "van_bumper_accessory_F_late": "",
        "van_converter": "van_converter_heavy",
        "van_differential_R": "van_differential_R_LSD",
        "van_door_FL": "van_door_FL",
        "van_door_FR": "van_door_FR",
        "van_doorglass_L": "van_doorglass_L",
        "van_doorglass_R": "van_doorglass_R",
        "van_doorpanel_FL": "van_doorpanel_FL",
        "van_doorpanel_FR": "van_doorpanel_FR",
        "van_driveshaft_R": "van_driveshaft_R",
        "van_engine": "van_engine_v8_5.5",
        "van_exhaust_v8": "van_exhaust_v8",
        "van_fascia_F": "van_fascia_F_late",
        "van_fender_L": "van_fender_L",
        "van_fender_R": "van_fender_R",
        "van_fenderflare_FL": "",
        "van_fenderflare_FR": "",
        "van_fenderflare_RL": "",
        "van_fenderflare_RR_sidedoor": "",
        "van_finaldrive_R": "van_finaldrive_R_355",
        "van_frame": "van_frame",
        "van_fueltank": "van_fueltank",
        "van_grille_F_late": "van_grille_F_late",
        "van_header": "van_exhmanifold",
        "van_headlight_L_late": "van_headlight_L_late",
        "van_headlight_R_late": "van_headlight_R_late",
        "van_hood": "van_hood_late",
        "van_hub_F": "van_hub_F_6",
        "van_hub_R": "van_hub_R_6",
        "van_intake_v8": "van_intake_v8_late",
        "van_intcarpet_roof": "",
        "van_interior": "van_interior",
        "van_lettering_doors_F": "van_lettering_doors_F_h25",
        "van_lettering_reardoor_L": "van_lettering_gavril_reardoor_L",
        "van_lettering_reardoor_R": "van_lettering_H25_reardoor_R",
        "van_licenseplate_F_late": "van_licenseplate_F_late",
        "van_licenseplate_R_late": "van_licenseplate_R_late",
        "van_lightbar": "",
        "van_load": "",
        "van_mirror_L": "van_mirror_L",
        "van_mirror_R": "van_mirror_R",
        "van_mod": "",
        "van_muffler": "van_muffler",
        "van_power_steering": "",
        "van_radiator": "van_radiator_heavy",
        "van_radio": "van_radio",
        "van_reardoor_L": "van_reardoor_L",
        "van_reardoor_R": "van_reardoor_R",
        "van_reardoorglass_L": "van_reardoorglass_L",
        "van_reardoorglass_R": "van_reardoorglass_R",
        "van_reardoorpanel_L": "",
        "van_reardoorpanel_R": "",
        "van_rollcage": "",
        "van_roof": "van_roof",
        "van_roof_accessory": "",
        "van_runningboard": "van_runningboard",
        "van_seat_FL": "van_seat_FL",
        "van_seat_FR": "van_seat_FR",
        "van_shifter": "van_shifter_A",
        "van_shock_F": "van_shock_F_medium",
        "van_shock_R": "van_shock_R_medium",
        "van_sidedoor_FR": "van_sidedoor_FR",
        "van_sidedoor_RR": "van_sidedoor_RR",
        "van_snorkel": "",
        "van_spring_F": "van_spring_F_medium",
        "van_spring_R": "van_spring_R_medium",
        "van_steer": "van_steer_facelift",
        "van_steering_SFA": "van_steering_SFA",
        "van_suspension_F": "van_beamaxle_F",
        "van_suspension_R": "van_axle_R",
        "van_swaybar_F_SFA": "",
        "van_swaybar_R": "",
        "van_taillight_L": "van_taillight_L",
        "van_taillight_R": "van_taillight_R",
        "van_taillightguard_L": "",
        "van_taillightguard_R": "",
        "van_transfer_case": "van_transfer_case_RWD",
        "van_transmission": "van_transmission_6A",
        "van_tubs": "van_tubs",
        "van_valance_F": "van_valance_F_late",
        "van_wheeldata_F": "van_wheeldata_F",
        "van_wheeldata_R": "van_wheeldata_R",
        "van_windshield": "van_windshield",
        "wheel_F_6": "roamer_alloy_16x7_F",
        "wheel_R_6": "roamer_alloy_16x7_R"
    },
    "vars": {
        "$steer_center_F2": 0.0001,
        "$tirepressure_F": 30,
        "$tirepressure_R": 30
    }
}

export const TESTED_MOD = 'GendarmerieNationaleSkinPack'
export const TESTED_VEHICLE = 'etk800'
export const EXPECTED_CONFIG = {
    pcFile: 'gendarmerie_new.pc',
    infoFile: 'info_gendarmerie_new.json',
    name: 'gendarmerie_new'
}

export const EXPECTED_INFO = {
    "Performance Class": "6",
    "Drivetrain": "RWD",
    "Body Style": "Wagon",
    "TorquePeakRPM": "2200 - 4300",
    "Weight": 1660,
    "Description": "Gendarmerie Nouvelle sérigraphie",
    "Configuration": "gendarmerie_new",
    "Config Type": "Police",
    "default_color": "Pearl White",
    "Transmission": "Automatic",
}

export const EXPECTED_PC = {
    "format": 2,
    "licenseName": "",
    "model": "etk800",
    "paints": [
        {
            "baseColor": [
                0.83,
                0.83,
                0.83,
                1.2
            ],
            "clearcoat": 1,
            "clearcoatRoughness": 0.03,
            "metallic": 0.3,
            "roughness": 0.6
        },
        {
            "baseColor": [
                0.83,
                0.83,
                0.83,
                1.2
            ],
            "clearcoat": 1,
            "clearcoatRoughness": 0.03,
            "metallic": 0.3,
            "roughness": 0.6
        },
        {
            "baseColor": [
                0.83,
                0.83,
                0.83,
                1.2
            ],
            "clearcoat": 1,
            "clearcoatRoughness": 0.03,
            "metallic": 0.3,
            "roughness": 0.6
        }
    ],
    "parts": {
        "brakepad_F": "brakepad_F_sport",
        "brakepad_R": "brakepad_R_sport",
        "etk800_DSE": "etk800_DSE",
        "etk800_DSE_ABS": "etk800_DSE_ABS",
        "etk800_DSE_ESC": "etk800_DSE_ESC",
        "etk800_DSE_TC": "etk800_DSE_TC_RWD",
        "etk800_DSE_drivemodes": "etk800_DSE_drivemodes_ICE",
        "etk800_DSE_drivemodes_default": "etk800_DSE_drivemodes_default_comfort",
        "etk800_DSE_drivemodes_drift": "",
        "etk800_DSE_drivemodes_ttSport": "",
        "etk800_body": "etk800_body_wagon",
        "etk800_brake_F": "etk800_brake_F",
        "etk800_brake_R": "etk800_brake_R",
        "etk800_bumper_F": "etk800_bumper_F",
        "etk800_bumper_R": "etk800_bumper_R",
        "etk800_bumperbar_F": "etk800_bumperbar_F",
        "etk800_differential_F": "",
        "etk800_differential_R": "etk800_differential_R",
        "etk800_diffuser_R": "etk800_diffuser_R_856",
        "etk800_door_FL": "etk800_door_FL",
        "etk800_door_FR": "etk800_door_FR",
        "etk800_door_RL_wagon": "etk800_door_RL_wagon",
        "etk800_door_RR_wagon": "etk800_door_RR_wagon",
        "etk800_doorglass_FL": "etk800_doorglass_FL",
        "etk800_doorglass_FR": "etk800_doorglass_FR",
        "etk800_doorglass_RL_wagon": "etk800_doorglass_RL_wagon",
        "etk800_doorglass_RR_wagon": "etk800_doorglass_RR_wagon",
        "etk800_doorpanel_FL": "etk800_doorpanel_FL",
        "etk800_doorpanel_FR": "etk800_doorpanel_FR",
        "etk800_doorpanel_RL": "etk800_doorpanel_RL",
        "etk800_doorpanel_RR": "etk800_doorpanel_RR",
        "etk800_driveshaft_R": "etk800_driveshaft_R",
        "etk800_exhausttips_i6": "etk800_exhausttips_i6",
        "etk800_fender_L": "etk800_fender_L",
        "etk800_fender_R": "etk800_fender_R",
        "etk800_finaldrive_R": "etk800_finaldrive_R_323",
        "etk800_fueltank": "etk800_fueltank",
        "etk800_glass_sunroof_wagon": "etk800_glass_sunroof_wagon",
        "etk800_halfshafts_R": "etk800_halfshafts_R",
        "etk800_headlight_L": "etk800_headlight_L",
        "etk800_headlight_R": "etk800_headlight_R",
        "etk800_hood": "etk800_hood",
        "etk800_lettering_tailgate": "etk800_lettering_tailgate_856t",
        "etk800_licenseplate_F": "",
        "etk800_licenseplate_R": "etk800_licenseplate_R",
        "etk800_lightbar": "etk800_blue_flat_lightbar",
        "etk800_lip_F": "",
        "etk800_mirror_L": "etk800_mirror_L",
        "etk800_mirror_R": "etk800_mirror_R",
        "etk800_mod": "",
        "etk800_power_steering": "",
        "etk800_quarterglass_L_wagon": "etk800_quarterglass_L_wagon",
        "etk800_quarterglass_R_wagon": "etk800_quarterglass_R_wagon",
        "etk800_radiator": "etk800_radiator",
        "etk800_roof_accessory": "",
        "etk800_roof_wagon": "etk800_roof_wagon_sun",
        "etk800_seat_FL": "etk800_seat_FL",
        "etk800_seat_FR": "etk800_seat_FR",
        "etk800_seats_R": "etk800_seats_R",
        "etk800_shifter": "etk800_shifter_M",
        "etk800_shock_R": "etk800_shock_R",
        "etk800_spoiler": "",
        "etk800_spring_R": "etk800_spring_R",
        "etk800_steer": "etk800_steer",
        "etk800_steering": "etk800_steering",
        "etk800_strut_F": "etk800_strut_F",
        "etk800_strutbrace_F": "etk800_strutbrace_F",
        "etk800_suspension_F": "etk800_suspension_F",
        "etk800_suspension_R": "etk800_suspension_R",
        "etk800_swaybar_F": "etk800_swaybar_F",
        "etk800_swaybar_R": "etk800_swaybar_R",
        "etk800_tailgate": "etk800_tailgate",
        "etk800_tailgateglass": "etk800_tailgateglass",
        "etk800_taillight_L": "etk800_taillight_L",
        "etk800_taillight_R": "etk800_taillight_R",
        "etk800_towhitch": "",
        "etk800_wheeldata_F": "etk800_wheeldata_F",
        "etk800_wheeldata_R": "etk800_wheeldata_R",
        "etk800_windshield": "etk800_windshield",
        "etk_engine": "etk_engine_i6",
        "etk_engine_ecu_speedlimit": "etk_engine_ecu_speedlimit_250",
        "etk_engine_i6_ecu": "etk_engine_i6_ecu",
        "etk_engine_i6_internals": "etk_engine_i6_internals",
        "etk_enginemounts": "etk_enginemounts",
        "etk_exhaust_i6_petrol": "etk_exhaust_i6_petrol",
        "etk_flywheel": "etk_flywheel",
        "etk_intake_i6": "etk_intake_i6",
        "etk_oilpan_i6": "etk_oilpan_i6",
        "etk_transfer_case": "etk_transfer_case_RWD",
        "etk_transmission": "etk_transmission_6M",
        "gps": "",
        "licenseplate_design_2_1": "",
        "linelock": "",
        "n2o_system": "",
        "paint_design": "etk800_gendarmerie_new",
        "skin_gauges": "etk800_gauges_imperial",
        "skin_interior": "etk800_skin_interior",
        "soundscape_horn": "soundscape_horn_7",
        "soundscape_siren": "soundscape_siren_gendarmerie",
        "tire_F_18x9": "tire_F_245_40_18_sport",
        "tire_R_18x9": "tire_R_245_40_18_sport",
        "wheel_F_5": "etk_wheel_03a_18x9_F",
        "wheel_R_5": "etk_wheel_03a_18x9_R"
    },
    "vars": {}
}
