 singleton Material("hopper.skin.Gendarmerie")
  {
   mapTo = "hopper.skin.Gendarmerie";
   overlayMap[2] = "vehicles/hopper/Gendarmerie/hopper_skin_Gendarmerie.dds";
   diffuseMap[2] = "vehicles/hopper/hopper_c.dds";
   specularMap[2] = "vehicles/hopper/hopper_s.dds";
   normalMap[2] = "vehicles/hopper/hopper_n.dds";
   diffuseMap[1] = "vehicles/hopper/hopper_d.dds";
   specularMap[1] = "vehicles/hopper/hopper_s.dds";
   normalMap[1] = "vehicles/hopper/hopper_n.dds";
   diffuseMap[0] = "vehicles/common/null.dds";
   specularMap[0] = "vehicles/common/null.dds";
   normalMap[0] = "vehicles/hopper/hopper_n.dds";
   specularPower[0] = "128";
   pixelSpecular[0] = "1";
   specularPower[1] = "32";
   pixelSpecular[1] = "1";
   specularPower[2] = "128";
   pixelSpecular[2] = "1";
   diffuseColor[0] = "1 1 1 1";
   diffuseColor[1] = "1 1 1 1";
   diffuseColor[2] = "1 1 1 1";
   useAnisotropic[0] = "1";
   useAnisotropic[1] = "1";
   useAnisotropic[2] = "1";
   castShadows = "1";
   translucent = "1";
   translucentBlendOp = "None";
   alphaTest = "0";
   alphaRef = "0";
   dynamicCubemap = true; //cubemap = "BNG_Sky_02_cubemap";
   instanceDiffuse[2] = true;
   materialTag0 = "beamng"; materialTag1 = "vehicle";
   };